import type { Category, WordEntry } from '../types';

/**
 * Word bank. Each entry carries 3 hints that are handed to the impostor —
 * they must be true of the word but never identify it outright, so the
 * impostor can bluff plausibly and still get caught by a sharp group.
 */
const w = (word: string, ...hints: string[]): WordEntry => ({ word, hints });

const FOOD: WordEntry[] = [
  w('Pizza', 'Shared at parties', 'Comes in a box', 'Italian roots'),
  w('Sushi', 'Often raw', 'Eaten with sticks', 'Rolled up'),
  w('Tacos', 'Folded', 'Has a night named after it', 'Street food'),
  w('Pancakes', 'Stacked', 'Weekend morning', 'Something sweet on top'),
  w('Ice Cream', 'Melts fast', 'Comes in scoops', 'Summer favourite'),
  w('Spaghetti', 'Long strands', 'Twirled', 'Red sauce'),
  w('Burger', 'Stacked layers', 'Fast food staple', 'Held in two hands'),
  w('Ramen', 'Steaming bowl', 'Slurped', 'Cheap student meal'),
  w('Chocolate', 'Melts in your hand', 'Given as a gift', 'Comes in bars'),
  w('Popcorn', 'Cinema smell', 'Pops', 'Eaten by the handful'),
  w('Dumplings', 'Wrapped parcels', 'Steamed', 'Dipped in sauce'),
  w('Caesar Salad', 'Leafy', 'Croutons', 'Named after a person'),
  w('Fried Chicken', 'Crispy coating', 'Eaten with fingers', 'Bucket'),
  w('Curry', 'Spicy', 'Served with rice', 'Many regional versions'),
  w('Waffles', 'Grid pattern', 'Syrup', 'Breakfast treat'),
  w('Donut', 'Has a hole', 'Glazed', 'Police stereotype'),
  w('Hot Dog', 'In a bun', 'Stadium food', 'Mustard'),
  w('Burrito', 'Wrapped tight', 'Foil', 'Mexican-ish'),
  w('Cheese', 'Ages well', 'Smelly varieties', 'Comes from milk'),
  w('Pho', 'Broth', 'Herbs on top', 'Vietnamese'),
  w('Steak', 'Cooked to a preference', 'Expensive cut', 'Needs a sharp knife'),
  w('Croissant', 'Flaky layers', 'Crescent shape', 'French bakery'),
  w('Smoothie', 'Blended', 'Through a straw', 'Fruit'),
  w('Pretzel', 'Twisted', 'Salted', 'German markets'),
  w('Nachos', 'Loaded', 'Shared plate', 'Melted topping'),
  w('Bacon', 'Sizzles', 'Breakfast', 'Strips'),
  w('Pasta Carbonara', 'Creamy', 'Egg and pork', 'Roman dish'),
  w('Bubble Tea', 'Chewy pearls', 'Wide straw', 'Taiwanese'),
  w('Cereal', 'Milk poured on', 'Cartoon mascots', 'Morning bowl'),
  w('Kebab', 'On a skewer', 'Late night food', 'Grilled meat'),
  w('Toast', 'Browned', 'Butter', 'Pops up'),
  w('Birthday Cake', 'Candles', 'Sung to', 'Sliced for a crowd'),
  w('Garlic Bread', 'Pungent', 'Side dish', 'Buttered'),
  w('Lasagna', 'Layered', 'Baked in a tray', 'A cat loves it'),
  w('Coffee', 'Bitter', 'Morning ritual', 'Keeps you awake'),
];

const ANIMALS: WordEntry[] = [
  w('Elephant', 'Never forgets', 'Very large', 'Grey and wrinkled'),
  w('Penguin', 'Wears a tuxedo look', 'Cannot fly', 'Very cold home'),
  w('Kangaroo', 'Hops', 'Carries young', 'Australian'),
  w('Dolphin', 'Very intelligent', 'Clicks and whistles', 'Lives in water'),
  w('Octopus', 'Many arms', 'Changes colour', 'Squeezes through gaps'),
  w('Giraffe', 'Very tall', 'Spotted pattern', 'Reaches high leaves'),
  w('Owl', 'Nocturnal', 'Head turns far', 'Symbol of wisdom'),
  w('Shark', 'Feared swimmer', 'Rows of teeth', 'Fin above water'),
  w('Panda', 'Black and white', 'Eats bamboo', 'Chinese symbol'),
  w('Snake', 'No legs', 'Sheds skin', 'Some are venomous'),
  w('Butterfly', 'Was something else first', 'Delicate wings', 'Visits flowers'),
  w('Crocodile', 'Ancient looking', 'Big jaws', 'Lurks in rivers'),
  w('Flamingo', 'Stands on one leg', 'Pink', 'Wading bird'),
  w('Hedgehog', 'Spiky', 'Curls into a ball', 'Small and nocturnal'),
  w('Wolf', 'Hunts in a group', 'Howls', 'Ancestor of pets'),
  w('Chameleon', 'Blends in', 'Long tongue', 'Independent eyes'),
  w('Peacock', 'Shows off', 'Fan display', 'Iridescent'),
  w('Sloth', 'Extremely slow', 'Hangs upside down', 'Rainforest'),
  w('Jellyfish', 'No brain', 'Stings', 'Translucent drifter'),
  w('Raccoon', 'Masked face', 'Raids bins', 'Nimble paws'),
  w('Tiger', 'Striped', 'Solitary hunter', 'Big cat'),
  w('Bat', 'Navigates by sound', 'Sleeps upside down', 'Flies at night'),
  w('Seahorse', 'Males carry young', 'Tiny', 'Curled tail'),
  w('Gorilla', 'Chest beating', 'Very strong', 'Close relative to us'),
  w('Koala', 'Sleeps most of the day', 'Eucalyptus', 'Australian tree dweller'),
  w('Cheetah', 'Fastest sprinter', 'Spotted', 'Tear marks on face'),
  w('Bee', 'Works for a queen', 'Makes something sweet', 'Pollinates'),
  w('Polar Bear', 'Arctic', 'White coat', 'Strong swimmer'),
  w('Ostrich', 'Cannot fly', 'Very fast runner', 'Huge eggs'),
  w('Frog', 'Starts life swimming', 'Croaks', 'Jumps'),
  w('Whale', 'Largest animal', 'Sings', 'Comes up to breathe'),
  w('Camel', 'Stores reserves', 'Desert transport', 'Humps'),
  w('Squirrel', 'Buries food', 'Bushy tail', 'Climbs trees'),
  w('Eagle', 'Sharp eyesight', 'National symbol', 'Soars high'),
  w('Crab', 'Walks sideways', 'Pincers', 'Hard shell'),
];

const PLACES: WordEntry[] = [
  w('Beach', 'Sandy', 'Waves', 'Holiday spot'),
  w('Airport', 'Lots of waiting', 'Security checks', 'Departures'),
  w('Hospital', 'Uniforms', 'You hope not to stay', 'Emergency'),
  w('Cinema', 'Dark room', 'Big screen', 'Shared silence'),
  w('Library', 'Quiet', 'Borrowing', 'Shelves'),
  w('Casino', 'No clocks', 'Chips', 'The house wins'),
  w('Zoo', 'Enclosures', 'Family day out', 'Feeding times'),
  w('School', 'Bells', 'Timetables', 'Where you grow up'),
  w('Gym', 'Sweaty', 'January crowds', 'Mirrors'),
  w('Supermarket', 'Trolleys', 'Aisles', 'Weekly trip'),
  w('Space Station', 'No gravity', 'Very few people', 'Orbit'),
  w('Submarine', 'Underwater', 'Cramped', 'Periscope'),
  w('Castle', 'Old stone', 'Defensive', 'Tourists photograph it'),
  w('Desert Island', 'Isolated', 'Castaway', 'Surrounded by water'),
  w('Ski Resort', 'Cold', 'Slopes', 'Lifts'),
  w('Circus', 'Big tent', 'Performers', 'Under the spotlight'),
  w('Museum', 'Do not touch', 'Old things', 'Guided tours'),
  w('Nightclub', 'Loud', 'Dark and crowded', 'Queue outside'),
  w('Farm', 'Early mornings', 'Animals', 'Fields'),
  w('Pirate Ship', 'Sails', 'Treasure', 'Crew of thieves'),
  w('Restaurant', 'Menus', 'Tipping', 'Someone serves you'),
  w('Train Station', 'Platforms', 'Announcements', 'Rush hour'),
  w('Amusement Park', 'Queues', 'Screaming', 'Rides'),
  w('Haunted House', 'Creaks', 'People get scared', 'Supposedly empty'),
  w('Prison', 'Bars', 'Sentences', 'Guards'),
  w('Church', 'Pews', 'Ceremonies', 'Bells'),
  w('Rooftop', 'Above everything', 'City views', 'Access restricted'),
  w('Petrol Station', 'Quick stop', 'Snacks', 'Pumps'),
  w('Hotel Lobby', 'Check-in', 'Strangers passing through', 'Luggage'),
  w('Volcano', 'Dangerous', 'Erupts', 'Hot'),
  w('Rainforest', 'Humid', 'Dense', 'Loud with life'),
  w('Stadium', 'Roaring crowd', 'Seats in tiers', 'Match day'),
  w('Hair Salon', 'Chairs and mirrors', 'Small talk', 'Scissors'),
  w('Post Office', 'Queues', 'Stamps', 'Parcels'),
  w('Aquarium', 'Glass tanks', 'Blue light', 'Family visit'),
];

const SCREEN: WordEntry[] = [
  w('Titanic', 'Ends badly', 'Ship', 'Famous romance'),
  w('Harry Potter', 'Magic school', 'Scar', 'Long series'),
  w('Star Wars', 'Space saga', 'Laser swords', 'Family drama'),
  w('Friends', 'Six of them', 'Coffee shop', 'Nineties sitcom'),
  w('Breaking Bad', 'Teacher turns bad', 'Desert', 'Chemistry'),
  w('The Office', 'Mockumentary', 'Awkward boss', 'Workplace'),
  w('Squid Game', 'Deadly contest', 'Childhood games', 'Korean'),
  w('Jurassic Park', 'Very old creatures', 'Theme park gone wrong', 'Island'),
  w('Frozen', 'Animated', 'Sisters', 'A song everyone knows'),
  w('The Lion King', 'Animated', 'Succession story', 'African setting'),
  w('Game of Thrones', 'Many houses', 'Divisive ending', 'Dragons'),
  w('Stranger Things', 'Kids on bikes', 'Eighties', 'Another dimension'),
  w('Avengers', 'Team of heroes', 'Crossover', 'Saving the world'),
  w('Toy Story', 'Animated', 'They move when you leave', 'Childhood'),
  w('The Matrix', 'Reality questioned', 'Green tint', 'Chosen one'),
  w('Spider-Man', 'Teenager hero', 'Swings', 'Uncle advice'),
  w('Shrek', 'Animated', 'Swamp', 'Subverts fairy tales'),
  w('Money Heist', 'Red suits', 'Robbery', 'Spanish'),
  w('The Simpsons', 'Yellow', 'Runs forever', 'Suburban family'),
  w('Inception', 'Layers', 'Confusing ending', 'Sleeping'),
  w('Wednesday', 'Gothic teen', 'Dance scene', 'Spin-off'),
  w('Peaky Blinders', 'Flat caps', 'Birmingham', 'Family crime'),
  w('Interstellar', 'Space', 'Time bends', 'Farming crisis'),
  w('Home Alone', 'Christmas', 'Left behind', 'Traps'),
  w('The Godfather', 'Family business', 'An offer', 'Crime epic'),
  w('Black Mirror', 'Anthology', 'Technology gone wrong', 'Bleak'),
  w('Sherlock', 'Deduction', 'London', 'Sidekick doctor'),
  w('Narcos', 'Drug trade', 'Colombia', 'Based on real events'),
  w('Barbie', 'Very pink', 'Toy come to life', 'Recent blockbuster'),
  w('Minecraft', 'Blocks', 'Building', 'Not really a film'),
];

const SPORT: WordEntry[] = [
  w('Football', 'Most popular globally', 'Goals', 'Eleven a side'),
  w('Basketball', 'Tall players', 'Hoop', 'Dribbling'),
  w('Chess', 'No luck involved', 'Turn based', 'Kings and queens'),
  w('Tennis', 'Net in the middle', 'Love means zero', 'Rackets'),
  w('Cricket', 'Very long matches', 'Wickets', 'Popular in India'),
  w('Swimming', 'Lanes', 'Goggles', 'Wet'),
  w('Boxing', 'Rounds', 'Gloves', 'One on one'),
  w('Marathon', 'Very long', 'Endurance', 'Started in Greece'),
  w('Golf', 'Small ball', 'Quiet crowd', 'Clubs'),
  w('Yoga', 'Mats', 'Breathing', 'Poses'),
  w('Skateboarding', 'Wheels', 'Tricks', 'Street culture'),
  w('Formula 1', 'Very fast', 'Pit stops', 'Global circuit'),
  w('Poker', 'Bluffing', 'Chips', 'Reading people'),
  w('Bowling', 'Pins', 'Heavy ball', 'Rented shoes'),
  w('Surfing', 'Waves', 'Board', 'Balance'),
  w('Table Tennis', 'Small ball', 'Fast reflexes', 'Indoor'),
  w('Badminton', 'Light projectile', 'Net', 'Racket sport'),
  w('Climbing', 'Ropes', 'Upward', 'Grip strength'),
  w('Hide and Seek', 'Counting', 'Childhood', 'Someone searches'),
  w('Darts', 'Pub game', 'Throwing', 'Board on a wall'),
  w('Ice Hockey', 'Cold surface', 'Sticks', 'Fights break out'),
  w('Rugby', 'Physical', 'Oval ball', 'Scrums'),
  w('Cycling', 'Two wheels', 'Tour races', 'Helmets'),
  w('Gymnastics', 'Flexibility', 'Judged', 'Beams and bars'),
  w('Monopoly', 'Board game', 'Ends in arguments', 'Property'),
  w('Volleyball', 'Beach version exists', 'Net', 'Spiking'),
  w('Archery', 'Aiming', 'Ancient weapon', 'Target rings'),
  w('Fishing', 'Patience', 'Waiting by water', 'Bait'),
  w('Karaoke', 'Lyrics on screen', 'Usually bad', 'Microphone'),
  w('Video Games', 'Controllers', 'Screen time', 'Levels'),
];

const OBJECTS: WordEntry[] = [
  w('Umbrella', 'Opens up', 'Weather related', 'Often lost'),
  w('Toothbrush', 'Twice a day', 'Bristles', 'Very personal'),
  w('Mirror', 'Reflects', 'Bad luck if broken', 'On a wall'),
  w('Phone', 'Always nearby', 'Battery anxiety', 'Screen'),
  w('Keys', 'Jingle', 'Always misplaced', 'Opens things'),
  w('Wallet', 'Pocket sized', 'Holds cards', 'Bad to lose'),
  w('Candle', 'Flickers', 'Wax', 'Blown out'),
  w('Backpack', 'Straps', 'School years', 'Carries things'),
  w('Sunglasses', 'Worn on the face', 'Bright days', 'Also a fashion item'),
  w('Alarm Clock', 'Universally hated', 'Beeps', 'Bedside'),
  w('Washing Machine', 'Spins', 'Eats socks', 'Household appliance'),
  w('Headphones', 'Blocks the world out', 'Wires or not', 'On your ears'),
  w('Pillow', 'Soft', 'Nightly', 'Fights with them'),
  w('Scissors', 'Two blades', 'Left-handed problem', 'Cuts'),
  w('Ladder', 'Steps', 'Superstition about walking under', 'Reaching high'),
  w('Vacuum Cleaner', 'Noisy', 'Sucks', 'Chores'),
  w('Passport', 'Small book', 'Terrible photo', 'Border control'),
  w('Suitcase', 'Wheels', 'Travel', 'Weighed at check-in'),
  w('Fridge', 'Hums', 'Magnets on it', 'Cold'),
  w('Guitar', 'Strings', 'Campfire', 'Six of something'),
  w('Camera', 'Captures moments', 'Lens', 'Click'),
  w('Bicycle', 'Two wheels', 'Never forget how', 'Pedals'),
  w('Wallet Chain', 'Attached', 'Punk look', 'Anti-theft'),
  w('Board Game', 'Boxed', 'Rules argued over', 'Rainy day'),
  w('Blanket', 'Wrapped in it', 'Warmth', 'Sofa companion'),
  w('Lightbulb', 'Screwed in', 'Idea symbol', 'Burns out'),
  w('Remote Control', 'Fought over', 'Buttons', 'Between the cushions'),
  w('Coffee Mug', 'Handle', 'Office desk', 'Stains'),
  w('Shoelaces', 'Tied', 'Come undone', 'Two of them'),
  w('Diary', 'Private', 'Dated entries', 'Locked sometimes'),
];

export const CATEGORIES: Category[] = [
  { id: 'food', name: 'Food & Drink', emoji: '🍕', words: FOOD },
  { id: 'animals', name: 'Animals', emoji: '🦁', words: ANIMALS },
  { id: 'places', name: 'Places', emoji: '🏝️', words: PLACES },
  { id: 'screen', name: 'Movies & TV', emoji: '🎬', words: SCREEN },
  { id: 'sport', name: 'Sport & Games', emoji: '⚽', words: SPORT },
  { id: 'objects', name: 'Everyday Things', emoji: '🧦', words: OBJECTS },
];

export function getCategory(id: string): Category {
  return CATEGORIES.find((c) => c.id === id) ?? CATEGORIES[0];
}

export const TOTAL_WORDS = CATEGORIES.reduce((n, c) => n + c.words.length, 0);
